# Generated by Django 5.1.1 on 2024-09-18 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, verbose_name='期日')),
            ],
            options={
                'verbose_name': 'Todoリスト',
                'verbose_name_plural': 'Todoリスト',
            },
        ),
    ]
