# Generated by Django 5.1.1 on 2024-10-01 13:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FootPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_footprint', to=settings.AUTH_USER_MODEL)),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_footprint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
